# Generated by Django 3.2.16 on 2022-12-04 12:19

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time_zone',
            field=models.CharField(help_text='Customer time zone.', max_length=50, validators=[mainapp.validators.validate_time_zone]),
        ),
    ]
