# Generated by Django 3.2.16 on 2022-12-04 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_customer_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_code',
            field=models.CharField(help_text='Mobile operator phone code, 3 digits.', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Phone number of the customer in format: 7XXXXXXXXXX.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Format should be "7XXXXXXXXXX" where X is digit.', regex='^7\\d{10}$')]),
        ),
    ]
